version: '3.8'
services:
  database: 
    container_name: ecomm-database-postgres
    image: postgres:16beta2-alpine
    environment:
      POSTGRES_DB: ecommercedatabase
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ecommdb
    ports:
      - "5433:5432"
    volumes:
      - ${PWD}/database/:/docker-entrypoint-initdb.d

